version: '3.8'
services:
  server:
    container_name: dion-server
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    container_name: dion-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - '5432:5432'
    volumes: 
      - ./.docker/volumes/db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
